In [1]:
import mwdsbe
import mwdsbe.datasets.licenses as licenses
import schuylkill as skool
import numpy as np
import pandas as pd

In [2]:
registry = mwdsbe.load_registry()
len(registry)

3119

In [3]:
license = licenses.CommercialActivityLicenses().download()
len(license)

203407

In [4]:
def exact_match(data1, data2, on, how):
    
    if how not in ["exact", "contains", "startswith"]:
        raise ValueError("how should be one of: 'exact', 'contains', 'startswith'")
    
    merged = skool.exact_merge(data1, data2, on=on, how=how)
    matched = merged.dropna(subset=['company_name_y'])
    
    return matched

In [5]:
def fuzzy_match(data1, data2, on, score_cutoff):
    
    merged = skool.fuzzy_merge(data1, data2, on=on, score_cutoff=score_cutoff)
    matched = merged.dropna(subset=["company_name_y"])
    
    return matched

In [6]:
def get_match_rate(original, matched):
    return len(matched) / len(original) * 100

In [7]:
mini_registry = registry[:100]

# clean company_name and dba name
ignore = ['inc', 'group', 'llc', 'corp', 'pc', 'incorporated', 'ltd']
cleaned_registry = skool.clean_strings(registry, ['company_name', 'dba_name'], True, ignore)
cleaned_mini_registry = skool.clean_strings(mini_registry, ['company_name', 'dba_name'], True, ignore)
cleaned_license = skool.clean_strings(license, ['company_name'], True, ignore)

In [24]:
exact = exact_match(cleaned_mini_registry, cleaned_license, on="company_name", how="exact")

In [25]:
get_match_rate(cleaned_mini_registry, exact)

41.0

In [26]:
# exact_contains = exact_match(cleaned_mini_registry, cleaned_license, on="company_name", how="contains")

In [46]:
fuzzy_95 = fuzzy_match(cleaned_mini_registry, cleaned_license, on="company_name", score_cutoff=95)

get_match_rate(cleaned_mini_registry, fuzzy_95)

80.0

In [47]:
len(fuzzy_95)

80

In [18]:
fuzzy_90 = fuzzy_match(cleaned_mini_registry, cleaned_license, on="company_name", score_cutoff=90)

In [23]:
get_match_rate(cleaned_mini_registry, fuzzy_90)

55.00000000000001

In [29]:
fuzzy_85 = fuzzy_match(cleaned_mini_registry, cleaned_license, on="company_name", score_cutoff=85)

get_match_rate(cleaned_mini_registry, fuzzy_85)

73.0

In [34]:
# exact match for full cleaned data
full_exact = exact_match(cleaned_registry, cleaned_license, on="company_name", how="exact")
get_match_rate(cleaned_registry, exact)

42.51362616223148

In [54]:
len(full_exact)

1326

In [50]:
# fuzzy match with 95 score_cutoff for full data
# full_fuzzy_95 = fuzzy_match(cleaned_registry, cleaned_license, on="company_name", score_cutoff=95)
# get_match_rate(cleaned_registry, full_fuzzy_95)

full_fuzzy_95_copy = pd.read_excel(r'C:\Users\dabinlee\Desktop\mwdsbe\data\full_clean_fuzzy_95.xlsx', index = None)

In [52]:
len(full_fuzzy_95_copy)

1345

In [53]:
get_match_rate(cleaned_registry, full_fuzzy_95_copy)

43.122795767874315

In [37]:
full_exact.to_excel (r'C:\Users\dabinlee\Desktop\mwdsbe\data\full_clean_exact.xlsx', index = None, header=True)

In [10]:
full_fuzzy_95.to_excel (r'C:\Users\dabinlee\Desktop\mwdsbe\data\full_clean_fuzzy_95.xlsx', index = None, header=True)

NameError: name 'full_fuzzy_95' is not defined

In [69]:
diff = full_fuzzy_95_copy[full_fuzzy_95_copy['match_probability'] == 0.95]
diff

,company_name_x,dba_name,owner_first,owner_last,location,location_city,location_state,zip_code,mailing_address,mailing_city,...,location_standard,lat,lng,geometry,match_probability,right_index,license_num,issue_date,license_status,company_name_y
165,billy boy contracting,NaN,Eddie,Hendrick,424 Bluebuff Road,King Of Prussia,PA,19406.0,424 Bluebuff Road,King Of Prussia,...,NaN,NaN,NaN,NaN,0.95,143959,545932,2011-10-07T00:00:00Z,Active,billy boy conttacting
172,blackridge construction,NaN,James,Carroll,1162 Grinnell Place,Bronx,NY,10474.0,1162 Grinnell Place,Bronx,...,NaN,NaN,NaN,NaN,0.95,36571,171176,2004-08-20T00:00:00Z,Active,ackridge construction
195,briones consulting engineering,NaN,Rolando,Briones,11742 Elmscourt,San Antonio,TX,78230.0,11742 Elmscourt,San Antonio,...,NaN,NaN,NaN,NaN,0.95,134681,495980,2010-03-17T00:00:00Z,Active,briones consulting engineering lt
256,charles e day and associates,NaN,Charles,Day,"211 N. Union Street, Suite 100",Alexandria,VA,22314.0,"211 N. Union Street, Suite 100",Alexandria,...,NaN,NaN,NaN,NaN,0.95,126813,457162,2008-09-23T00:00:00Z,Active,charles e day sr and associates
313,contractor compliance,NaN,Andis,Woodlief,1724 Baldwin Rd,Yorktown Heights,NY,10598.0,1724 Baldwin Rd,Yorktown Heights,...,NaN,NaN,NaN,NaN,0.95,78937,12374,2005-01-28T00:00:00Z,Active,contract compliance
352,de carvalho,NaN,Fabio,DeCarvalho,614 Taylor Street,Riverside,PA,8075.0,614 Taylor Street,Riverside,...,NaN,NaN,NaN,NaN,0.95,159482,623793,2014-04-02T00:00:00Z,Active,de cavalho
378,diversifi consulting,NaN,Lori,Daly,112 N Jay Street,Middleburg,VA,20117.0,P.O. Box 1461,Middleburg,...,NaN,NaN,NaN,NaN,0.95,70070,50639,2005-01-28T00:00:00Z,Active,diversified consulting
398,dw environmental consulting,NaN,Deborah,Wilson,12552 Silverdale St,Tampa,FL,33626.0,12552 Silverdale St,Tampa,...,NaN,NaN,NaN,NaN,0.95,165011,650933,2014-12-26T00:00:00Z,Active,dcr environmental consulting
403,e r cleaning services,NaN,Estelle,Martin,4351 N. Fairhill Street,Philadelphia,PA,19140.0,4351 N. Fairhill Street,Philadelphia,...,4351 N FAIRHILL ST,40.017936,-75.136228,POINT (-75.13622801793933 40.01793612224625),0.95,146784,558886,2012-03-26T00:00:00Z,Active,e e cleaning services
513,general excavating and demolition,NaN,Frances,Cortes,"2023 Wakleling Street, PO BOX 9531",Philadelphia,PA,19124.0,"2023 Wakleling Street, PO BOX 9531",Philadelphia,...,2023 WAKELING ST,40.013380,-75.073380,POINT (-75.07338015208299 40.01338040406193),0.95,101407,342028,2005-10-24T00:00:00Z,Active,general excavating and demolit
532,global marine construction supply,NaN,YONA,BOCCHIO,55 LUMBER ROAD - SUITE 125,Roslyn,NY,11576.0,55 LUMBER ROAD - SUITE 125,Roslyn,...,NaN,NaN,NaN,NaN,0.95,121627,432348,2008-01-14T00:00:00Z,Active,global marine construction sup
586,hoon ho oh builders contractors,NaN,Hoon,Ho Oh,5813 Thomas Avenue,Philadelphia,PA,19143.0,5813 Thomas Avenue,Philadelphia,...,5813 THOMAS AVE,39.942461,-75.237244,POINT (-75.23724437571967 39.94246141361558),0.95,24622,147899,2001-10-09T00:00:00Z,Active,hoon ho oh builders contract
587,hope health systems,NaN,Monica,Trish,"6707 White Stone Road, Suite 106",Woodlawn,MD,21207.0,"6707 White Stone Road, Suite 106",Woodlawn,...,NaN,NaN,NaN,NaN,0.95,90453,194661,2005-01-28T00:00:00Z,Active,home health systems
622,international pioneer marketing,NaN,Adam,Kim,4240-42 North Broad Street,Philadelphia,PA,19140.0,4240-42 North Broad Street,Philadelphia,...,4240-42 N BROAD ST,40.018066,-75.149866,POINT (-75.1498657534149 40.0180655768587),0.95,27226,151005,2002-07-26T00:00:00Z,Active,international pioneer market
696,l r construction co,NaN,Judith,Vollmer,35 Kresson Rd,Cherry Hill,NJ,8034.0,P.O. Box 215,Haddonfield,...,NaN,NaN,NaN,NaN,0.95,21490,133634,2000-10-20T00:00:00Z,Active,s r construction co
734,locating utility infrastructure services,NaN,Luis,Berrios,7801 E Roosevelt Blvd. #11,Philadelphia,PA,19152.0,7801 E Roosevelt Blvd. #11,Philadelphia,...,7801 E ROOSEVELT BLVD,40.054356,-75.047851,POINT (-75.04785118750249 40.05435594260746),0.95,148574,569094,2012-07-18T00:00:00Z,Active,locating utility infrastructure serv
756,maddox behavioral health services,NaN,Hillerie,Maddox,7045 Sherwood Road,Philadelphia,PA,19151.0,7045 Sherwood Road,Philadelphia,...,7045 SHERWOOD RD,39.981145,-75.263070,POINT (-75.26307036466322 39.98114513956367),0.95,93311,178587,2005-02-12T00:00:00Z,Active,maddox behavioral health servi
779,mathews nielsen landscape architects p c,mathews nielsen mnla,Signe,Nielsen,"120 Broadway, Suite 1040",New York,NY,10271.0,"120 Broadway, Suite 1040",New York,...,NaN,NaN,NaN,NaN,0.95,131454,481830,2009-08-26T00:00:00Z,Active,mathews nielsen landscape architects
811,mkg global solutions,NaN,Mariska,Bogle,728 S. Clifton Street,Philadelphia,PA,19147.0,728 S. Clifton Street,Philadelphia,...,728 S CLIFTON ST,39.941367,-75.160154,POINT (-75.16015393771232 39.94136708574449),0.95,145914,554501,2012-02-12T00:00:00Z,Active,mkb global solutions
814,mobilestrat,NaN,Larry,Blackshear,642 Cowpath Road #390,Lansdale,PA,19446.0,642 Cowpath Road #390,Lansdale,...,NaN,NaN,NaN,NaN,0.95,38380,185238,2004-12-20T00:00:00Z,Active,mobilstrat
818,monbo international,NaN,Dee,Monbo,"10451 Mill Run Circle, Suite 400A",Owings Mills,MD,21117.0,"10451 Mill Run Circle, Suite 400A",Owings Mills,...,NaN,NaN,NaN,NaN,0.95,191444,777138,2018-05-17T00:00:00Z,Active,mondo international
830,ms technologies corporation,NaN,MEI-LING L.,CHENG,"10110 MOLECULAR DRIVE, SUITE 305",Rockville,MD,20850.0,"10110 MOLECULAR DRIVE, SUITE 305",Rockville,...,NaN,NaN,NaN,NaN,0.95,35836,170966,2004-07-09T00:00:00Z,Active,ehs technologies corporation
831,mt martin,NaN,Michael,Martin,473 Chapel Heights Road,Sewell,NJ,8080.0,473 Chapel Heights Road,Sewell,...,NaN,NaN,NaN,NaN,0.95,9811,4877,1997-04-04T00:00:00Z,Active,m t martin
975,ps energy,NaN,Livia,Whisenhunt,"4480 N. Shallowford Road, Suite 100",Dunwoody,GA,30338.0,"4480 N. Shallowford Road, Suite 100",Dunwoody,...,NaN,NaN,NaN,NaN,0.95,195993,796765,2018-12-11T00:00:00Z,Active,pes energy
1049,s b design,NaN,SHABNAM,BHATLA,822 ELDERBERRY LANE,West Chester,PA,19380.0,822 ELDERBERRY LANE,West Chester,...,NaN,NaN,NaN,NaN,0.95,116484,412545,2007-06-07T00:00:00Z,Active,sb design
1112,south jersey paper products,NaN,Bonnie,Spector,2400 Industrial Way,Vineland,NJ,8360.0,2400 Industrial Way,Vineland,...,NaN,NaN,NaN,NaN,0.95,93411,179725,2005-02-14T00:00:00Z,Active,south jersey paper products in
1285,v j supply,NaN,Vimall,Gupta,838 Sussex Blvd,Broomall,PA,19008.0,838 Sussex Blvd,Broomall,...,NaN,NaN,NaN,NaN,0.95,10406,104905,1997-05-31T00:00:00Z,Active,vj supply

In [71]:
diff.to_excel (r'C:\Users\dabinlee\Desktop\mwdsbe\data\full_fuzzy_95_correctness.xlsx', index = None, header=True)

In [16]:
# fuzzy match with 90 score_cutoff for full data
full_fuzzy_90 = fuzzy_match(cleaned_registry, cleaned_license, on="company_name", score_cutoff=90)
get_match_rate(cleaned_registry, full_fuzzy_90)

52.48477075985893

In [17]:
full_fuzzy_90.to_excel (r'C:\Users\dabinlee\Desktop\mwdsbe\data\full_clean_fuzzy_90.xlsx', index = None, header=True)

In [20]:
diff_exact_90 = full_fuzzy_90[full_fuzzy_90['match_probability'] < 1]
len(diff_exact_90)

429

In [19]:
diff_exact_90.to_excel (r'C:\Users\dabinlee\Desktop\mwdsbe\data\diff_exact_90.xlsx', index = None, header=True)

In [27]:
diff_95_90 = full_fuzzy_90[full_fuzzy_90['match_probability'] < 1]
diff_95_90 = diff_95_90[diff_95_90['match_probability'] > 0.9]
diff_95_90

,company_name_x,dba_name,owner_first,owner_last,location,location_city,location_state,zip_code,mailing_address,mailing_city,...,location_standard,lat,lng,geometry,match_probability,right_index,license_num,issue_date,license_status,company_name_y
1,12bravo,NaN,JEFFREY,YEKENCHIK,236 McKendimen Road,Medford Lakes,NJ,8055.0,236 McKendimen Road,Medford Lakes,...,NaN,NaN,NaN,None,0.93,200602.0,815623,2019-06-17T00:00:00Z,Active,12 bravo
7,24 hour cleaning services,NaN,Mary Colleen,Zoltowski,14005 Barcalow Street,Philadelphia,PA,19116.0,14005 Barcalow Street,Philadelphia,...,14005 BARCALOW ST,40.131349,-75.014284,POINT (-75.01428 40.13135),0.98,17320.0,120711,1999-08-30T00:00:00Z,Active,24 hour cleaning service
25,a bob s towing,NaN,Mikina,Harrison,2220 Orthodox Street,Philadelphia,PA,19137.0,2220 Orthodox Street,Philadelphia,...,2220 ORTHODOX ST,40.008166,-75.078701,POINT (-75.07870 40.00817),0.96,134133.0,134939,2010-02-04T00:00:00Z,Active,a bobs towing
34,a m electric,NaN,Anthony,Muhammad,2222 N. Marshall Street,Philadelphia,PA,19133.0,2222 N. Marshall Street,Philadelphia,...,2222 N MARSHALL ST,39.985489,-75.144539,POINT (-75.14454 39.98549),0.96,28710.0,154795,2002-11-27T00:00:00Z,Active,am electric
35,a m painting,NaN,Abdullah,Muhammad,2745 North Garnet Street,Philadelphia,PA,19132.0,2745 North Garnet Street,Philadelphia,...,2745 N GARNET ST,39.996079,-75.162692,POINT (-75.16269 39.99608),0.96,118226.0,419397,2007-08-06T00:00:00Z,Active,am painting
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3045,webster associates,NaN,Deborah,Webster,301 South Elm Street Suite 508,Greensboro,NC,27401.0,301 South Elm Street Suite 508,Greensboro,...,NaN,NaN,NaN,None,0.94,22355.0,131448,2001-01-22T00:00:00Z,Active,weber associates
3053,west construction services,NaN,Christine,Gallagher,264 Broadway Road,Merion,PA,19066.0,264 Broadway Road,Merion,...,NaN,NaN,NaN,None,0.96,105222.0,360580,2006-03-20T00:00:00Z,Active,best construction services
3064,williams electric,NaN,Richard,Williams,17 Karen Drive,Williamstown,NJ,8094.0,1532 S 53rd Street,Philadelphia,...,NaN,NaN,NaN,None,0.97,125874.0,453068,2008-08-04T00:00:00Z,Active,williams electrica
3073,wjj global enterprises,NaN,Willie,Jones,1242 Pratt Street,Philadelphia,PA,19124.0,1242 Pratt Street,Philadelphia,...,1242 PRATT ST,40.025222,-75.083344,POINT (-75.08334 40.02522),0.91,172657.0,687493,2015-12-30T00:00:00Z,Active,cjr global enterprises
3078,woodland wallker,NaN,Jeremy,Walker,4701 Woodland Avenue,Philadelphia,PA,19143.0,4701 Woodland Avenue,Philadelphia,...,4701 WOODLAND AVE,39.943011,-75.211579,POINT (-75.21158 39.94301),0.97,152394.0,590839,2013-04-20T00:00:00Z,Active,woodland walker

In [28]:
diff_95_90.to_excel (r'C:\Users\dabinlee\Desktop\mwdsbe\data\diff_95_90.xlsx', index = None, header=True)

In [8]:
# match company_name and dba_name
merged = (
    skool.fuzzy_merge(cleaned_mini_registry, cleaned_license, on="company_name", score_cutoff=95)
    .pipe(skool.fuzzy_merge, cleaned_mini_registry, cleaned_license, left_on="dba_name", right_on="company_name", score_cutoff=95)
)
matched = merged.dropna(subset=['company_name_y'])
matched

,company_name_x,dba_name,owner_first,owner_last,location,location_city,location_state,zip_code,mailing_address,mailing_city,...,location_standard,lat,lng,geometry,match_probability,right_index,license_num,issue_date,license_status,company_name_y
0,119 degrees architects,NaN,Rafael,Utrera,"1503 Green Street, Suite # 4",Philadelphia,PA,19130.0,"1503 Green Street, Suite # 4",Philadelphia,...,1503 GREEN ST,39.964275,-75.163042,POINT (-75.16304190105227 39.96427495800303),1,131110,480115,2009-07-31T00:00:00Z,Active,119 degrees architects
5,22,NaN,Caroline,Harper,757 Public Road,Bethlehem,PA,18015.0,757 Public Road,Bethlehem,...,NaN,NaN,NaN,NaN,1,168717,667661,2015-06-10T00:00:00Z,Active,22
7,24 hour cleaning services,NaN,Mary Colleen,Zoltowski,14005 Barcalow Street,Philadelphia,PA,19116.0,14005 Barcalow Street,Philadelphia,...,14005 BARCALOW ST,40.131349,-75.014284,POINT (-75.0142839608247 40.1313485259829),0.98,17315,120711,1999-08-30T00:00:00Z,Active,24 hour cleaning service
8,259 strategies,NaN,Chaka,"Fattah, Jr.","Two Logan Square, Suite 1900",Philadelphia,PA,19103.0,"Two Logan Square, Suite 1900",Philadelphia,...,100-20 N 18TH ST,39.955726,-75.169784,POINT (-75.16978354446475 39.95572609768801),1,102404,346817,2005-11-28T00:00:00Z,Active,259 strategies
12,4u services,stellar services,Liang,Chen,"70 West 36th Street, Ste. #702",New York,NY,10018.0,"70 West 36th Street, Ste. #702",New York,...,NaN,NaN,NaN,NaN,1,141063,531189,2011-04-22T00:00:00Z,Active,4u services
15,521 management,NaN,Kris,Bowman,"1000 1st Avenue, Suite 104",King Of Prussia,PA,19406.0,"1000 1st Avenue, Suite 104",King Of Prussia,...,NaN,NaN,NaN,NaN,1,26010,136428,2002-03-08T00:00:00Z,Active,521 management
16,6 degrees consulting,NaN,Robert,Lawson,"6545 Hamiton Avenue, Suite 1A",Ptttsburgh,PA,15206.0,"6545 Hamiton Avenue, Suite 1A",Ptttsburgh,...,NaN,NaN,NaN,NaN,1,171403,681851,2015-10-26T00:00:00Z,Active,6 degrees consulting
17,84 lumber company,84 lumber company,Margaret,Hardy-Knox,1019 Route 519,Eighty Four,PA,15330.0,1019 Route 519,Eighty Four,...,NaN,NaN,NaN,NaN,1,111884,393009,2006-11-30T00:00:00Z,Active,84 lumber company
18,a a court reporting,andrea st john,Andrea,St. John,"303 Chestnut Street, Second Floor",Philadelphia,PA,19106.0,"P.O. Box 74, Suite 4",Moorestown,...,303 CHESTNUT ST,39.948849,-75.146173,POINT (-75.14617317373323 39.94884851072602),1,154364,107405,2013-07-29T00:00:00Z,Active,a a court reporting
21,a c environmental services,NaN,ANTOINETTE,PATRICK,2045 NORTH LAWRENCE STREET,Philadelphia,PA,19122.0,2045 NORTH LAWRENCE STREET,Philadelphia,...,2045 N LAWRENCE ST,39.982290,-75.141137,POINT (-75.14113684169367 39.98229031987706),1,118975,122477,2007-09-07T00:00:00Z,Active,a c environmental services
22,a i security,NaN,RAYMOND,ALVAREZ,10234 Dedater Street,Philadelphia,PA,19116.0,10234 Dedater Street,Philadelphia,...,10234 DEDATER ST,40.106057,-75.018803,POINT (-75.01880335762779 40.10605658825222),1,174641,698635,2016-04-07T00:00:00Z,Active,a i security
25,a bob s towing,NaN,Mikina,Harrison,2220 Orthodox Street,Philadelphia,PA,19137.0,2220 Orthodox Street,Philadelphia,...,2220 ORTHODOX ST,40.008166,-75.078701,POINT (-75.07870119360095 40.008166153533),0.96,134138,134939,2010-02-04T00:00:00Z,Active,a bobs towing
29,a best vending,a best vending coffee service,Sue,Epstein,7336 State Rd,Philadelphia,PA,19136.0,7336 State Rd,Philadelphia,...,7336 STATE RD,40.026532,-75.030907,POINT (-75.03090690917051 40.02653173547168),1,110588,122115,2006-10-06T00:00:00Z,Active,a best vending
30,a m e mechanical,NaN,Alfred,Edmunds Jr,6123 Washington Ave,Philadelphia,PA,19143.0,6123 Washington Ave,Philadelphia,...,6123 WASHINGTON AVE,39.948499,-75.246577,POINT (-75.24657668245011 39.94849889264492),1,148569,569144,2012-07-18T00:00:00Z,Active,a m e mechanical
33,a lee cook hauling,NaN,Amy,Lee-Cook,643 Pennfield Drive,Hatfield,PA,19440.0,643 Pennfield Drive,Hatfield,...,NaN,NaN,NaN,NaN,1,176272,706507,2016-06-29T00:00:00Z,Active,a lee cook hauling
34,a m electric,NaN,Anthony,Muhammad,2222 N. Marshall Street,Philadelphia,PA,19133.0,2222 N. Marshall Street,Philadelphia,...,2222 N MARSHALL ST,39.985489,-75.144539,POINT (-75.14453871694691 39.9854885343929),0.96,28704,154795,2002-11-27T00:00:00Z,Active,am electric
35,a m painting,NaN,Abdullah,Muhammad,2745 North Garnet Street,Philadelphia,PA,19132.0,2745 North Garnet Street,Philadelphia,...,2745 N GARNET ST,39.996079,-75.162692,POINT (-75.16269177785369 39.99607919723243),0.96,118213,419397,2007-08-06T00:00:00Z,Active,am painting
37,a m truck auto repair,NaN,CATHY,MATARAZZO-NICHOLAS,14065 Townsend Road,Philadelphia,PA,19154.0,14065 Townsend Road,Philadelphia,...,14065 TOWNSEND RD,40.108419,-74.975170,POINT (-74.97516992544176 40.10841900796122),0.98,19875,131320,2000-05-25T00:00:00Z,Active,am truck auto repair
40,a v rental services,NaN,Bruce,Johnson,4039 Comly Street,Philadelphia,PA,19135.0,4039 Comly Street,Philadelphia,...,4039 COMLY ST,40.025665,-75.065982,POINT (-75.06598156425623 40.02566472515707),0.97,118940,422259,2007-09-06T00:00:00Z,Active,av rental services
48,abbadon corporation,superior facility service,Donna,Cohen,712 Bigler Street,Philadelphia,PA,19148.0,712 Bigler St,Philadelphia,...,712 BIGLER ST,39.912636,-75.161093,POINT (-75.16109345872107 39.91263606065034),1,103074,019267,2005-12-23T00:00:00Z,Active,abbadon corporation
49,abbi print,NaN,Abdoulaye,Coumbassa,321 S. 60th Street,Philadelphia,PA,19143.0,321 S. 60th Street,Philadelphia,...,321 S 60TH ST,39.955801,-75.241786,POINT (-75.24178642305672 39.95580104382807),1,152449,591018,2013-04-23T00:00:00Z,Active,abbi print
50,abbonizio transfer,NaN,Karen,Abbonizio,"416E S. Governor Printz Boulevard, PO Box 166",Lester,PA,19029.0,416E S. Governor Printz Boulevard,Lester,...,NaN,NaN,NaN,NaN,1,132216,132302,2009-10-15T00:00:00Z,Active,abbonizio transfer
51,abc construction co,NaN,KIMBERLY,NUGENT,714 Dunksferry Rd.,Bensalem,PA,19020.0,714 Dunksferry Rd.,Bensalem,...,NaN,NaN,NaN,NaN,1,1711,010250,1994-08-25T00:00:00Z,Active,abc construction co
52,abc multi language services,NaN,Chankia,Hourn-Quigley,"901 North Penn Street, Suite 1504",Philadelphia,PA,19123.0,"901 North Penn Street, Suite 1504",Philadelphia,...,901 N PENN ST,39.961707,-75.134510,POINT (-75.13450965840566 39.9617071789125),1,140693,529347,2011-04-01T00:00:00Z,Active,abc multi language services
56,abstract,NaN,Daniel S.,Kebede,1734 Chiswick CT,Silver Spring,MD,20904.0,1734 Chiswick CT,Silver Spring,...,NaN,NaN,NaN,NaN,1,182278,734777,2017-04-10T00:00:00Z,Active,abstract
58,ac s contractors,NaN,Megan,Caldarelli,7173 Charles Street,Philadelphia,PA,19135.0,7173 Charles Street,Philadelphia,...,7173 CHARLES ST,40.034781,-75.042004,POINT (-75.04200447618257 40.03478124916646),0.97,37477,190889,2004-10-25T00:00:00Z,Active,a s contractors
60,acacia financial,NaN,Noreen,White,"6000 Midlantic Drive, Suite 410 North",Mt. Laurel,NJ,8054.0,"6000 Midlantic Drive, Suite 410 North",Mt. Laurel,...,NaN,NaN,NaN,NaN,1,129488,471078,2009-04-15T00:00:00Z,Active,acacia financial
62,accelerated land transfer,NaN,Marsha,Wolf,"1845 Walnut Street, 25th Floor",Philadelphia,PA,19103.0,"1845 Walnut Street, 25th Floor",Philadelphia,...,1845 WALNUT ST,39.950665,-75.171552,POINT (-75.17155162505139 39.95066503792084),1,110118,383081,2006-09-19T00:00:00Z,Active,accelerated land transfer
63,access personnel services,NaN,Tyrone,Miller,38 - 42 W. Orange Street,Lancaster,PA,17603.0,38 - 42 W. Orange Street,Lancaster,...,NaN,NaN,NaN,NaN,1,135550,500487,2010-05-04T00:00:00Z,Active,access personnel services
64,accessibility modification solutions,NaN,Stamatia,Papanikolaou,"2818 E. Allegheny Ave, 2nd Fl",Philadelphia,PA,19134.0,"2818 E. Allegheny Ave, 2nd Fl",Philadelphia,...,2818 E ALLEGHENY AVE,39.982439,-75.101489,POINT (-75.1014894297461 39.98243882340253),1,178810,719871,2016-11-15T00:00:00Z,Active,accessibility modification solutions
66,accord mechanical management services,NaN,Ulrick,Joseph,218 E Washington Street,Norristown,PA,19401.0,218 E Washington Street,Norristown,...,NaN,NaN,NaN,NaN,0.96,8952,088671,1996-12-12T00:00:00Z,Active,accord mechanical management servi
67,accountants for you,NaN,Marcia,Libes,PO Box 1040,Cherry Hill,NJ,8034.0,PO Box 1040,Cherry Hill,...,NaN,NaN,NaN,NaN,1,110640,387213,2006-10-10T00:00:00Z,Active,accountants for you
69,accu fire fabrication,NaN,Deardra,Murphy,8 Progress Drive,Morrisville,PA,19067.0,8 Progress Drive,Morrisville,...,NaN,NaN,NaN,NaN,1,135279,498981,2010-04-20T00:00:00Z,Active,accu fire fabrication
71,accustar,touch pro,Lisa Ann,Mariotti,"3060 Plaza Drive, Suite 101",Garnet Valley,PA,19060.0,"3060 Plaza Drive, Suite 101",Garnet Valley,...,NaN,NaN,NaN,NaN,1,157081,613448,2013-12-27T00:00:00Z,Active,accustar
75,ack contracting,ack contracting,Brenda,Kellogg,18 Campus Blvd Ste 100,Newtown Square,PA,19073.0,18 Campus Blvd Ste 100,Newtown Square,...,NaN,NaN,NaN,NaN,1,197878,804592,2019-03-05T00:00:00Z,Active,ack contracting
77,acorn services,NaN,Deborah,Proctor LePera,"3553 West Chester Pike, # 401",Newtown Square,PA,19073.0,"3553 West Chester Pike, # 401",Newtown Square,...,NaN,NaN,NaN,NaN,1,123256,001818,2008-04-08T00:00:00Z,Active,acorn services
78,acp demolition remodeling,NaN,Dee-Thomas,Jones,720 Pines Wood Drive,Middletown,DE,19709.0,720 Pines Wood Drive,Middletown,...,NaN,NaN,NaN,NaN,1,180098,725597,2017-01-13T00:00:00Z,Active,acp demolition remodeling
82,acutedge,NaN,Sandeep,Banga,"5 Great Valley Parkway, Suite 210",Malvern,PA,19355.0,"5 Great Valley Parkway, Suite 210",Malvern,...,NaN,NaN,NaN,NaN,1,167445,661326,2015-04-16T00:00:00Z,Active,acutedge
85,adaptive resources,NaN,Eliseo,Rodriguez,104 Broadway Street,Carnegie,PA,15104.0,104 Broadway Street,Carnegie,...,NaN,NaN,NaN,NaN,1,169218,670235,2015-07-06T00:00:00Z,Active,adaptive resources
86,adcon consultants,NaN,Lawrence,Dibor,"2465 North 50th Street Bala Building, Suite #1...",Philadelphia,PA,19131.0,"2465 North 50th Street Bala Building, Suite #1...",Philadelphia,...,2465 N 50TH ST,39.999592,-75.227267,POINT (-75.22726709374048 39.99959159953162),1,10627,104755,1997-07-07T00:00:00Z,Active,adcon consultants
89,adg enterprises,NaN,Diana,Patterson,"3479 Lawrenceville - Suwanee Road, Suite B",Suwanee,GA,30024.0,"3479 Lawrenceville - Suwanee Road, Suite B",Suwanee,...,NaN,NaN,NaN,NaN,0.97,32016,168981,2003-10-06T00:00:00Z,Active,ag enterprises
90,adkins management,NaN,Sheila,Adkins,4113 Colonial Court,Valley Forge,PA,19403.0,4113 Colonial Court,Valley Forge,...,NaN,NaN,NaN,NaN,1,10716,100507,1997-07-16T00:00:00Z,Active,adkins management
92,admiral integration,NaN,Katiusca,McEntee,1001 Route 70 West,Cherry Hill,NJ,8002.0,1001 Route 70 West,Cherry Hill,...,NaN,NaN,NaN,NaN,1,151280,584611,2013-02-15T00:00:00Z,Active,admiral integration
93,adolphues building services,servicemaster janitorial by abs,ANTONIE,ADOLPHUES,5530 Litchfield Street,Philadelphia,PA,19143.0,5530 Litchfield Street,Philadelphia,...,5530 LITCHFIELD ST,39.940602,-75.228043,POINT (-75.22804268536242 39.94060173344999),1,193957,788165,2018-09-05T00:00:00Z,Active,adolphues building services
96,advanced disposal solutions,NaN,Suzanne,Dolaway,2200 Adams Avenue,Philadelphia,PA,19124.0,2200 Adams Avenue,Philadelphia,...,2200 ADAMS AVE,40.005190,-75.087504,POINT (-75.08750396797005 40.00518954853843),1,126252,135111,2008-08-22T00:00:00Z,Active,advanced disposal solutions
97,advanced hydraulic systems,NaN,Judith,Ward,727 East 9th Street,Chester,PA,19013.0,727 East 9th Street,Chester,...,NaN,NaN,NaN,NaN,1,10629,104763,1997-07-07T00:00:00Z,Active,advanced hydraulic systems
98,advanced infrastructure design,NaN,Mojgan,Mohtashami,1 Crossroads Drive,Hamilton,NJ,8691.0,1 Crossroads Drive,Hamilton,...,NaN,NaN,NaN,NaN,1,173140,689813,2016-01-28T00:00:00Z,Active,advanced infrastructure design
99,advanced integration,NaN,Donna,Chappel,"1 McCormick Road, Suite A",Mckees Rocks,PA,15136.0,"1 McCormick Road, Suite A",Mckees Rocks,...,NaN,NaN,NaN,NaN,1,29524,152902,2003-03-03T00:00:00Z,Active,advanced integration

In [13]:
dba = matched[matched['dba_name'].notna()]
dba

,company_name_x,dba_name,owner_first,owner_last,location,location_city,location_state,zip_code,mailing_address,mailing_city,...,location_standard,lat,lng,geometry,match_probability,right_index,license_num,issue_date,license_status,company_name_y
12,4u services,stellar services,Liang,Chen,"70 West 36th Street, Ste. #702",New York,NY,10018.0,"70 West 36th Street, Ste. #702",New York,...,NaN,NaN,NaN,None,1.0,141065.0,531189,2011-04-22T00:00:00Z,Active,4u services
17,84 lumber company,84 lumber company,Margaret,Hardy-Knox,1019 Route 519,Eighty Four,PA,15330.0,1019 Route 519,Eighty Four,...,NaN,NaN,NaN,None,1.0,111886.0,393009,2006-11-30T00:00:00Z,Active,84 lumber company
18,a a court reporting,andrea st john,Andrea,St. John,"303 Chestnut Street, Second Floor",Philadelphia,PA,19106.0,"P.O. Box 74, Suite 4",Moorestown,...,303 CHESTNUT ST,39.948849,-75.146173,POINT (-75.14617 39.94885),1.0,154361.0,107405,2013-07-29T00:00:00Z,Active,a a court reporting
29,a best vending,a best vending coffee service,Sue,Epstein,7336 State Rd,Philadelphia,PA,19136.0,7336 State Rd,Philadelphia,...,7336 STATE RD,40.026532,-75.030907,POINT (-75.03091 40.02653),1.0,110609.0,122115,2006-10-06T00:00:00Z,Active,a best vending
48,abbadon corporation,superior facility service,Donna,Cohen,712 Bigler Street,Philadelphia,PA,19148.0,712 Bigler St,Philadelphia,...,712 BIGLER ST,39.912636,-75.161093,POINT (-75.16109 39.91264),1.0,103092.0,019267,2005-12-23T00:00:00Z,Active,abbadon corporation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3034,walls engineering pllc,richard walls,Richard,Walls,"10911 Raven Ridge Road, Suite 103-76",Raleigh,NC,27614.0,"10911 Raven Ridge Road, Suite 103-76",Raleigh,...,NaN,NaN,NaN,None,1.0,198351.0,806486,2019-03-21T00:00:00Z,Active,walls engineering pllc
3037,wash cycle laundry,wash cycle laundry,Gabriel,Mandujano,"1617 JFK Boulevard, Suite - 1855",Philadelphia,PA,19103.0,"1617 JFK Boulevard, Suite - 1855",Philadelphia,...,1617 JOHN F KENNEDY BLVD,39.953873,-75.167082,POINT (-75.16708 39.95387),1.0,147085.0,560293,2012-04-10T00:00:00Z,Active,wash cycle laundry
3051,wendy saltzman media,philly power media,Wendy,Saltzman,1112 South 17th Street,Philadelphia,PA,19146.0,1112 South 17th Street,Philadelphia,...,1112 S 17TH ST,39.937827,-75.171934,POINT (-75.17193 39.93783),1.0,190358.0,772115,2018-04-09T00:00:00Z,Active,wendy saltzman media
3066,willow accounting consulting,willow accounting consulting,Miranda,Willow,"4811 Jonestown Road, Suite 224",Harrisburg,PA,17109.0,"4811 Jonestown Road, Suite 224",Harrisburg,...,NaN,NaN,NaN,None,1.0,182953.0,737961,2017-05-09T00:00:00Z,Active,willow accounting consulting
3086,wright commissioning,wright commissioning,Kim,Wright,"150 Monument Rd, Suite 101",Bala Cynwyd,PA,19004.0,"150 Monument Rd, Suite 101",Bala Cynwyd,...,NaN,NaN,NaN,None,1.0,149742.0,575500,2012-10-11T00:00:00Z,Active,wright commissioning

In [55]:
# match just dba_name
fuzzy_dba_merged = skool.fuzzy_merge(cleaned_registry, cleaned_license, left_on="dba_name", right_on="company_name", score_cutoff=96)
fuzzy_dba_matched = fuzzy_dba_merged.dropna(subset=['company_name_y'])
fuzzy_dba_matched

,company_name_x,dba_name,owner_first,owner_last,location,location_city,location_state,zip_code,mailing_address,mailing_city,...,location_standard,lat,lng,geometry,match_probability,right_index,license_num,issue_date,license_status,company_name_y
17,84 lumber company,84 lumber company,Margaret,Hardy-Knox,1019 Route 519,Eighty Four,PA,15330.0,1019 Route 519,Eighty Four,...,NaN,NaN,NaN,None,1.00,111891.0,393009,2006-11-30T00:00:00Z,Active,84 lumber company
48,abbadon corporation,superior facility service,Donna,Cohen,712 Bigler Street,Philadelphia,PA,19148.0,712 Bigler St,Philadelphia,...,712 BIGLER ST,39.912636,-75.161093,POINT (-75.16109 39.91264),1.00,178880.0,720072,2016-11-16T00:00:00Z,Active,superior facility service
75,ack contracting,ack contracting,Brenda,Kellogg,18 Campus Blvd Ste 100,Newtown Square,PA,19073.0,18 Campus Blvd Ste 100,Newtown Square,...,NaN,NaN,NaN,None,1.00,197892.0,804592,2019-03-05T00:00:00Z,Active,ack contracting
169,alpha office supplies,alpha enterprise,Terrill L,Brown,"4950 Parkside Avenue, Suite 500",Philadelphia,PA,19131.0,P O BOX 2361,Bala Cynwyd,...,4950 PARKSIDE AVE,39.979714,-75.218697,POINT (-75.21870 39.97971),0.97,172752.0,687938,2016-01-06T00:00:00Z,Active,alpha enterprises
170,alpha omega systems services medical supply,aoss medical supply,Hon K,Liew,4971 Central Avenue,Monroe,LA,71203.0,4971 Central Avenue,Monroe,...,NaN,NaN,NaN,None,1.00,149271.0,573020,2012-09-06T00:00:00Z,Active,aoss medical supply
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001,vic thompson company,vtc,Christine,Norton,"3751 New York Avenue, Suite 140",Arlington,TX,76014.0,"3751 New York Avenue, Suite 140",Arlington,...,NaN,NaN,NaN,None,1.00,145436.0,552631,2012-01-19T00:00:00Z,Active,vtc
3005,virgo iii,virgo iii,Anne,Manuel,766 Knox Court,Yardley,PA,19067.0,766 Knox Court,Yardley,...,NaN,NaN,NaN,None,1.00,94092.0,191740,2005-03-02T00:00:00Z,Active,virgo iii
3037,wash cycle laundry,wash cycle laundry,Gabriel,Mandujano,"1617 JFK Boulevard, Suite - 1855",Philadelphia,PA,19103.0,"1617 JFK Boulevard, Suite - 1855",Philadelphia,...,1617 JOHN F KENNEDY BLVD,39.953873,-75.167082,POINT (-75.16708 39.95387),1.00,147066.0,560293,2012-04-10T00:00:00Z,Active,wash cycle laundry
3066,willow accounting consulting,willow accounting consulting,Miranda,Willow,"4811 Jonestown Road, Suite 224",Harrisburg,PA,17109.0,"4811 Jonestown Road, Suite 224",Harrisburg,...,NaN,NaN,NaN,None,1.00,182964.0,737961,2017-05-09T00:00:00Z,Active,willow accounting consulting
3086,wright commissioning,wright commissioning,Kim,Wright,"150 Monument Rd, Suite 101",Bala Cynwyd,PA,19004.0,"150 Monument Rd, Suite 101",Bala Cynwyd,...,NaN,NaN,NaN,None,1.00,149739.0,575500,2012-10-11T00:00:00Z,Active,wright commissioning

In [68]:
fuzzy_dba_matched[0.95 < fuzzy_dba_matched['match_probability']]

,company_name_x,dba_name,owner_first,owner_last,location,location_city,location_state,zip_code,mailing_address,mailing_city,...,location_standard,lat,lng,geometry,match_probability,right_index,license_num,issue_date,license_status,company_name_y
17,84 lumber company,84 lumber company,Margaret,Hardy-Knox,1019 Route 519,Eighty Four,PA,15330.0,1019 Route 519,Eighty Four,...,NaN,NaN,NaN,None,1.00,111891.0,393009,2006-11-30T00:00:00Z,Active,84 lumber company
48,abbadon corporation,superior facility service,Donna,Cohen,712 Bigler Street,Philadelphia,PA,19148.0,712 Bigler St,Philadelphia,...,712 BIGLER ST,39.912636,-75.161093,POINT (-75.16109 39.91264),1.00,178880.0,720072,2016-11-16T00:00:00Z,Active,superior facility service
75,ack contracting,ack contracting,Brenda,Kellogg,18 Campus Blvd Ste 100,Newtown Square,PA,19073.0,18 Campus Blvd Ste 100,Newtown Square,...,NaN,NaN,NaN,None,1.00,197892.0,804592,2019-03-05T00:00:00Z,Active,ack contracting
169,alpha office supplies,alpha enterprise,Terrill L,Brown,"4950 Parkside Avenue, Suite 500",Philadelphia,PA,19131.0,P O BOX 2361,Bala Cynwyd,...,4950 PARKSIDE AVE,39.979714,-75.218697,POINT (-75.21870 39.97971),0.97,172752.0,687938,2016-01-06T00:00:00Z,Active,alpha enterprises
170,alpha omega systems services medical supply,aoss medical supply,Hon K,Liew,4971 Central Avenue,Monroe,LA,71203.0,4971 Central Avenue,Monroe,...,NaN,NaN,NaN,None,1.00,149271.0,573020,2012-09-06T00:00:00Z,Active,aoss medical supply
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001,vic thompson company,vtc,Christine,Norton,"3751 New York Avenue, Suite 140",Arlington,TX,76014.0,"3751 New York Avenue, Suite 140",Arlington,...,NaN,NaN,NaN,None,1.00,145436.0,552631,2012-01-19T00:00:00Z,Active,vtc
3005,virgo iii,virgo iii,Anne,Manuel,766 Knox Court,Yardley,PA,19067.0,766 Knox Court,Yardley,...,NaN,NaN,NaN,None,1.00,94092.0,191740,2005-03-02T00:00:00Z,Active,virgo iii
3037,wash cycle laundry,wash cycle laundry,Gabriel,Mandujano,"1617 JFK Boulevard, Suite - 1855",Philadelphia,PA,19103.0,"1617 JFK Boulevard, Suite - 1855",Philadelphia,...,1617 JOHN F KENNEDY BLVD,39.953873,-75.167082,POINT (-75.16708 39.95387),1.00,147066.0,560293,2012-04-10T00:00:00Z,Active,wash cycle laundry
3066,willow accounting consulting,willow accounting consulting,Miranda,Willow,"4811 Jonestown Road, Suite 224",Harrisburg,PA,17109.0,"4811 Jonestown Road, Suite 224",Harrisburg,...,NaN,NaN,NaN,None,1.00,182964.0,737961,2017-05-09T00:00:00Z,Active,willow accounting consulting
3086,wright commissioning,wright commissioning,Kim,Wright,"150 Monument Rd, Suite 101",Bala Cynwyd,PA,19004.0,"150 Monument Rd, Suite 101",Bala Cynwyd,...,NaN,NaN,NaN,None,1.00,149739.0,575500,2012-10-11T00:00:00Z,Active,wright commissioning

In [16]:
fuzzy_dba_matched.to_excel (r'C:\Users\dabinlee\Desktop\mwdsbe\data\full_clean_dba_fuzzy_95.xlsx', index = None, header=True)

In [48]:
# fuzzywuzzy with token_set_ratio - ignore punc, order, and duplicates
full_fuzzy_95_token_set_ratio = fuzzy_match(cleaned_registry, cleaned_license, on="company_name", score_cutoff=95)

In [54]:
len(full_fuzzy_95_token_set_ratio)

1345

In [20]:
# check fuzzy.ratio -> fuzzy.token_set_ratio
fuzzy_tsr = fuzzy_match(cleaned_mini_registry, cleaned_license, on="company_name", score_cutoff=95)
# len(fuzzy_tsr)

In [21]:
len(fuzzy_tsr)

80

In [25]:
fuzzy_tsr[['company_name_x', 'match_probability', 'company_name_y']]

,company_name_x,match_probability,company_name_y
0,119 degrees architects,1.0,119 degrees architects
5,22,1.0,22 continue
6,24 asset management,1.0,24 management
7,24 hour cleaning services,1.0,cleaning services
8,259 strategies,1.0,259 strategies
...,...,...,...
95,advance detective bureau t a d o richardson,1.0,d t
96,advanced disposal solutions,1.0,advanced disposal solutions
97,advanced hydraulic systems,1.0,advanced hydraulic systems
98,advanced infrastructure design,1.0,design
99,advanced integration,1.0,advanced integration

In [36]:
# check fuzzy.ratio -> fuzzy.partial_ratio
fuzzy_pr = fuzzy_match(cleaned_mini_registry, cleaned_license, on="company_name", score_cutoff=95)
# len(fuzzy_tsr)

len(fuzzy_pr)

fuzzy_pr[['company_name_x', 'match_probability', 'company_name_y']]

,company_name_x,match_probability,company_name_y
0,119 degrees architects,1.0,119 degrees architects
5,22,1.0,22 continue
6,24 asset management,1.0,24 management
7,24 hour cleaning services,1.0,cleaning services
8,259 strategies,1.0,259 strategies
...,...,...,...
95,advance detective bureau t a d o richardson,1.0,d t
96,advanced disposal solutions,1.0,advanced disposal solutions
97,advanced hydraulic systems,1.0,advanced hydraulic systems
98,advanced infrastructure design,1.0,design
99,advanced integration,1.0,advanced integration

In [44]:
# check fuzzy.ratio -> fuzzy.partial_ratio
fuzzy_r = fuzzy_match(cleaned_mini_registry, cleaned_license, on="company_name", score_cutoff=95)
# len(fuzzy_tsr)

len(fuzzy_r)

fuzzy_r[['company_name_x', 'match_probability', 'company_name_y']]

,company_name_x,match_probability,company_name_y
0,119 degrees architects,1.0,119 degrees architects
5,22,1.0,22 continue
6,24 asset management,1.0,24 management
7,24 hour cleaning services,1.0,cleaning services
8,259 strategies,1.0,259 strategies
...,...,...,...
95,advance detective bureau t a d o richardson,1.0,d t
96,advanced disposal solutions,1.0,advanced disposal solutions
97,advanced hydraulic systems,1.0,advanced hydraulic systems
98,advanced infrastructure design,1.0,design
99,advanced integration,1.0,advanced integration

In [19]:
# pipe all: exact, fuzzy_95 on company_name, fuzzy_95 on dba_name

In [ ]:
# store data into excel

#     path = r'C:\Users\dabinlee\Desktop\mwdsbe\data\clean_fuzzy_merge'
#     path.join(['_', str(score_cutoff), '.xlsx'])
    
#     export_excel = matched.to_excel(path, index = None, header=True)

In [ ]:
# get_match_rate(cleaned_mini_registry, exact_contains)

# exact_contains.to_excel (r'C:\Users\dabinlee\Desktop\mwdsbe\data\clean_exact_contains.xlsx', index = None, header=True)